### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by stefanjudis** [3rd-party-bouncer/chrome-bouncer#1]
## Functionality improvements
- [ ] make it possible to decide to show # of requests or # of domains to show in topbar and save it in local storage or anything
## Data improvements
- [ ] use spof check to give a hint about render blocking scripts inside `head` 
- [x] show requests per domain
  - [ ] show size and timing of request per domain
- [ ] show total weight and total number of request per domain `abc.com 79 req | 500KB`
## UI improvements
- [ ] include bouncer logo in a nice manner. :)
- [x] include bouncer logo in shorthand topbar
- [ ] show overall total weight and total number of requests
  - [ ] add a checkbox to include or exclude a 3rd party domain from total at the bottom
- [x] add detail view for one domain?! ( @radimir get crazy!!! )
- [ ] detect if adblocker is switched on and tell the user if so ( results are not valid then )
- [ ] add a settings dialog

Inspiration:
- https://codepen.io/ettrics/pen/Jdjdzp
